#hub_router_1.0.1/docker-compose.gateway.yml

services:
  api_gateway:
    container_name: api_gateway
    build:
      context: ./src/api_gateway
      dockerfile: Dockerfile.api_gateway
    ports:
      - "8010:8000"
    volumes:
      - ./src:/app/src
      - ./exports:/app/exports
    env_file:
      - ./src/api_gateway/.env
    environment:
      - PYTHONPATH=/app/src
    networks:
      - hub_router_network
    restart: always

networks:
  hub_router_network:
    external: true