name: cluster_router
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - pandas
      - numpy
      - psycopg2-binary
      - sqlalchemy
      - python-dotenv
      - scikit-learn
      - streamlit
      - matplotlib
      - seaborn
      - requests
      - uvicorn
      - fastapi
      - openpyxl
      - plotly