FROM psilas85/hub_router-base:latest

# Define o diretório de trabalho
WORKDIR /app

# Copia o código fonte
COPY src/ /app/src

# Variável de ambiente para encontrar módulos Python
ENV PYTHONPATH=/app/src

# Porta padrão do serviço
EXPOSE 8005

# Comando de inicialização do serviço de custos de transferências
CMD ["uvicorn", "costs_transfer.api.main:app", "--host", "0.0.0.0", "--port", "8005"]
