FROM psilas85/hub_router-base:latest

# Define o diretório de trabalho
WORKDIR /app

# Copia o código fonte
COPY src/ /app/src

# Variável de ambiente para encontrar módulos Python
ENV PYTHONPATH=/app/src

# Porta padrão do serviço
EXPOSE 8000

# Comando de inicialização do serviço de autenticação
CMD ["uvicorn", "authentication.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
