FROM psilas85/hub_router-base:latest

WORKDIR /app

# Copia src e requirements
COPY ./src /app/src
COPY requirements.txt /app/

# Instala dependências
RUN pip install --no-cache-dir -r requirements.txt

# Porta interna (reserva, quando formos expor FastAPI)
ENV SERVICE_PORT=8014
EXPOSE 8014

# Define PYTHONPATH para o src
ENV PYTHONPATH=/app/src

# Executa script de validação inicial
CMD ["uvicorn", "machine_learning.api.main:app", "--host", "0.0.0.0", "--port", "8014"]



