#hub_router_1.0.1/src/data_input/Dockerfile.data_input

FROM psilas85/hub_router-base:latest

WORKDIR /app

# 🔥 1. instala dependências (cache forte)
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# 🔥 2. copia código depois (evita invalidar pip install)
COPY src/ /app/src

ENV PYTHONPATH=/app/src

EXPOSE 8008

CMD ["uvicorn", "data_input.api.main:app", "--host", "0.0.0.0", "--port", "8008"]